// Generated by Sideko (sideko.dev)
package canva_connect_api

import (
	"fmt"
	"net/http"
)

type UnexpectedResponseCodeError struct {
	StatusCode            int
	Method                string
	Url                   string
	Data                  []byte
	Request               http.Request
	Response              http.Response
	ExpectedResponseCodes []string
}

func (e UnexpectedResponseCodeError) Error() string {
	return fmt.Sprintf("Unexpected status code received %d from %s %s, handlers set up for: %+v", e.StatusCode, e.Method, e.Url, e.ExpectedResponseCodes)
}
