// Generated by Sideko (sideko.dev)
package canva_connect_api

type ListAllDesignsRequest struct {
	Continuation *string                  `json:"continuation,omitempty"`
	Ownership    *GetDesignsOwnershipEnum `json:"ownership,omitempty"`
	Query        *string                  `json:"query,omitempty"`
	SortBy       *GetDesignsSortByEnum    `json:"sortBy,omitempty"`
}
