# Generated by Sideko (sideko.dev)
# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name        = 'canva_connect_api'
  spec.summary     = 'canva_connect_api 0.1.0'
  spec.version     = '0.1.0'
  spec.description = 'The Canva Connect API facilitates third-party app developers to extend key Canva capabilities off-platform. It allows Canva to share data with third parties, even when a user is not actively designing in Canva.
You can use the Canva Connect API to create integrations with third-party apps, keep Canva in sync with cloud storage and content management apps, collaborate and communicate with different platforms, or embed Canva into project management workflows.
For instance, you could create an integration (we call this a client) between Canva and your digital asset management system using the Connect API, to create Canva folders and upload your assets directly to these folders.
This is in contrast to the Canva App SDKs which bring third-party capabilities to Canva (on-platform), to enhance user experience designing in Canva.
'
  spec.authors     = ['Sideko']
  spec.email       = 'team@sideko.dev'
  spec.license     = 'MIT'
  spec.files       = ['lib/canva_connect_api.rb']

  spec.add_runtime_dependency 'http', '~> 5.1.1'
end