// Generated by Sideko (sideko.dev)
import { AxiosResponseHeaders, RawAxiosResponseHeaders } from "axios";
import { ReadStream } from "fs";

export class BinaryResponse {
  content: ArrayBuffer;
  headers: AxiosResponseHeaders | RawAxiosResponseHeaders;

  constructor(content: ArrayBuffer, headers: AxiosResponseHeaders | RawAxiosResponseHeaders) {
    this.content = content;
    this.headers = headers;
}
}


export type TeamUser = {
  "display_name"?: string
  "team_id"?: string
  "user_id"?: string

}
  

export type Thumbnail = {
  "height"?: number
  "url"?: string
  "width"?: string

}
  

export type Design = {
  "doctype_name"?: string
  "id"?: string
  "owner"?: TeamUser
  "thumbnail"?: Thumbnail
  "title"?: string

}
  

export type GetDesignsResponse = {
  "continuation"?: string
  "items"?: Design[]

}
  

export enum GetDesignsOwnershipEnum {
  Owned = "OWNED",
  Shared = "SHARED",
  Any = "ANY",
}
export enum GetDesignsSortByEnum {
  Relevance = "RELEVANCE",
  ModifiedDescending = "MODIFIED_DESCENDING",
  ModifiedAscending = "MODIFIED_ASCENDING",
  TitleDescending = "TITLE_DESCENDING",
  TitleAscending = "TITLE_ASCENDING",
}
